#!/bin/sh
DAEMON=/home/root/hermes2_startup.sh
#DAEMONSRC=/media/sd-mmcblk0p2/hermes2_startup.sh
#DAEMONSRC=/innophase/hermes2_startup.sh
DAEMONSRC=/innophase/hermes2_startup.sh

start()
{
	echo " Starting hermes2-init"
#	if [ ! -f $DAEMON ]; then
#		cp -f $DAEMONSRC $DAEMON
#	fi
	chmod +x $DAEMON
	start-stop-daemon -S -o -x $DAEMON
}
stop()
{
	echo " Stoping hermes2-init"
	start-stop-daemon -K -x $DAEMON
}
restart()
{
	stop
	start
}
#[ -e $DAEMONSRC ] || exit 1
[ -e $DAEMON ] || exit 1
	case "$1" in
		start)
			start; ;;
		stop)
			stop; ;;
		restart)
			restart; ;;
		*)
			echo "Usage: $0 {start:stop:restart}"
			exit 1
	esac
exit $?
