/*  test-drv.c - The simplest kernel module.

* Copyright (C) 2013 - 2016 Xilinx, Inc
*
*   This program is free software; you can redistribute it and/or modify
*   it under the terms of the GNU General Public License as published by
*   the Free Software Foundation; either version 2 of the License, or
*   (at your option) any later version.

*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License along
*   with this program. If not, see <http://www.gnu.org/licenses/>.

*/
#include <linux/kernel.h>
#include <linux/device.h>
#include <linux/cdev.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/io.h>
#include <linux/interrupt.h>
#include <linux/param.h>
#include <linux/fs.h>
#include <linux/types.h>
#include <linux/uaccess.h>
#include <linux/jiffies.h>

#include <linux/of_address.h>
#include <linux/of_device.h>
#include <linux/of_platform.h>

#define DEBUG
/* Standard module information, edit as appropriate */
MODULE_LICENSE("GPL");
MODULE_AUTHOR
    ("PW.");
MODULE_DESCRIPTION
    ("test-drv - loadable module template generated by petalinux-create -t modules");

#define DRIVER_NAME "test-drv"
#define PPP(x) printk(x)
/* Simple example of how to receive command line parameters to your module.
   Delete if you don't need them */
unsigned myint = 0xdeadbeef;
char *mystr = "default";

module_param(myint, int, S_IRUGO);
module_param(mystr, charp, S_IRUGO);

static struct class *test_drv_driver_class; /* char device class */



struct test_drv_local {
	int irq;
	unsigned long mem_start;
	unsigned long mem_end;
	void __iomem *base_addr;
	unsigned int test1;
	unsigned int test2;
	unsigned int test3;

	
	
	struct device *dt_device; /* device created from the device tree */
	struct device *device; /* device associated with char_device */
	dev_t devt; /* our char device number */
	struct cdev char_device; /* our char device */
	
	
};
#define TEST1_OFFSET 0
#define TEST2_OFFSET 1
#define TEST3_OFFSET 2
/* ----------------------------
 *         sysfs entries
 * ----------------------------
 */

static ssize_t sysfs_write(struct device *dev, const char *buf,
			   size_t count, unsigned int addr_offset)
{
	struct test_drv_local *lp = dev_get_drvdata(dev);
	unsigned long tmp;
	int rc;

	rc = kstrtoul(buf, 0, &tmp);
	if (rc < 0)
		return rc;

	//iowrite32(tmp, lp->base_addr + addr_offset);

	return count;
}

static ssize_t sysfs_read(struct device *dev, char *buf,
			  unsigned int addr_offset)
{
	struct test_drv_local *lp = dev_get_drvdata(dev);
	unsigned int read_val;
	unsigned int len;
	char tmp[32];

	//read_val = ioread32(lp->base_addr + addr_offset);
	read_val=*(&lp->test1+addr_offset*sizeof(unsigned int));
	len =  snprintf(tmp, sizeof(tmp), "0x%x\n", read_val);
	memcpy(buf, tmp, len);
	return len;
}


static ssize_t test1_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count)
{
	return sysfs_write(dev, buf, count, TEST1_OFFSET);
}


static ssize_t test2_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count)
{
	return sysfs_write(dev, buf, count, TEST2_OFFSET);
}

static ssize_t test3_store(struct device *dev, struct device_attribute *attr,
			 const char *buf, size_t count)
{
	return sysfs_write(dev, buf, count, TEST3_OFFSET);
}


static ssize_t test1_show(struct device *dev,
			struct device_attribute *attr, char *buf)
{
	return sysfs_read(dev, buf, TEST1_OFFSET);
}

static DEVICE_ATTR_RW(test1);

static ssize_t test2_show(struct device *dev,
			struct device_attribute *attr, char *buf)
{
	return sysfs_read(dev, buf, TEST2_OFFSET);
}

static DEVICE_ATTR_RW(test2);

static ssize_t test3_show(struct device *dev,
			struct device_attribute *attr, char *buf)
{
	return sysfs_read(dev, buf, TEST3_OFFSET);
}

static DEVICE_ATTR_RW(test3);




static struct attribute *test_drv_attrs[] = {
	&dev_attr_test1.attr,
	&dev_attr_test2.attr,
	&dev_attr_test3.attr,
	NULL,
};

static const struct attribute_group test_drv_attrs_group = {
	.name = "test_registers",
	.attrs = test_drv_attrs,
};

static const struct file_operations fops = {
	.owner = THIS_MODULE,
// 	.open = axis_fifo_open,
// 	.release = axis_fifo_close,
// 	.unlocked_ioctl = axis_fifo_ioctl,
// 	.read = axis_fifo_read,
// 	.write = axis_fifo_write,
// 	.poll = axis_poll
};



/* read named property from the device tree */
static int get_dts_property(struct test_drv_local *lp,
			    char *name, unsigned int *var)
{
	int rc;

	rc = of_property_read_u32(lp->dt_device->of_node, name, var);
	if (rc) {
		dev_err(lp->dt_device, "couldn't read IP dts property '%s'",
			name);
		return rc;
	}
	dev_dbg(lp->dt_device, "dts property '%s' = %u\n",
		name, *var);

	return 0;
}


static irqreturn_t test_drv_irq(int irq, void *lp)
{
	printk("test-drv interrupt\n");
	return IRQ_HANDLED;
}




static int test_drv_probe(struct platform_device *pdev)
{
	struct resource *r_irq; /* Interrupt resources */
	struct resource *r_mem; /* IO mem resources */
	struct device *dev = &pdev->dev;
	struct test_drv_local *lp = NULL;
	char device_name[32];

	int rc = 0;
	dev_info(dev, "Device Tree Probing\n");
	/* Get iospace for the device */
	r_mem = platform_get_resource(pdev, IORESOURCE_MEM, 0);
	if (!r_mem) {
		dev_err(dev, "invalid address\n");
		return -ENODEV;
	}
	lp = (struct test_drv_local *) kmalloc(sizeof(struct test_drv_local), GFP_KERNEL);
	if (!lp) {
		dev_err(dev, "Cound not allocate test-drv device\n");
		return -ENOMEM;
	}
	dev_set_drvdata(dev, lp);
	lp->dt_device = dev;
	lp->mem_start = r_mem->start;
	lp->mem_end = r_mem->end;
	
	if (!request_mem_region(lp->mem_start,
				lp->mem_end - lp->mem_start + 1,
				DRIVER_NAME)) {
		dev_err(dev, "Couldn't lock memory region at %p\n",
			(void *)lp->mem_start);
		rc = -EBUSY;
		goto error1;
	}

	lp->base_addr = ioremap(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	if (!lp->base_addr) {
		dev_err(dev, "test-drv: Could not allocate iomem\n");
		rc = -EIO;
		goto error2;
	}

// 	/* Get IRQ for the device */
// 	r_irq = platform_get_resource(pdev, IORESOURCE_IRQ, 0);
// 	if (!r_irq) {
// 		dev_info(dev, "no IRQ found\n");
// 		dev_info(dev, "test-drv at 0x%08x mapped to 0x%08x\n",
// 			(unsigned int __force)lp->mem_start,
// 			(unsigned int __force)lp->base_addr);
// 		return 0;
// 	}
// 	lp->irq = r_irq->start;
// 	rc = request_irq(lp->irq, &test_drv_irq, 0, DRIVER_NAME, lp);
// 	if (rc) {
// 		dev_err(dev, "testmodule: Could not allocate interrupt %d.\n",
// 			lp->irq);
// 		goto error3;
// 	}
// 
		/* create unique device name */
	snprintf(device_name, sizeof(device_name), "%s_%pa",
		 DRIVER_NAME, &lp->mem_start);

	dev_dbg(lp->dt_device, "device name [%s]\n", device_name);

		/* retrieve device tree properties */
	rc = get_dts_property(lp, "test1",
			      &lp->test1);
	if (rc)
		goto err_unmap;
	rc = get_dts_property(lp, "test2",
			      &lp->test2);
	if (rc)
		goto err_unmap;
	rc = get_dts_property(lp, "test3",
			      &lp->test3);
	if (rc)
		goto err_unmap;

	
	
	dev_info(dev,"test-drv at 0x%08x mapped to 0x%08x, irq=%d\n",
		(unsigned int __force)lp->mem_start,
		(unsigned int __force)lp->base_addr,
		lp->irq);
	
	rc = alloc_chrdev_region(&lp->devt, 0, 1, DRIVER_NAME);
	if (rc < 0)
		goto err_irq;
	dev_dbg(lp->dt_device, "allocated device number major %i minor %i\n",
		MAJOR(lp->devt), MINOR(lp->devt));

	
	printk("TEST Drv name %s,devt %d \r\n",device_name,lp->devt);
	
		/* create driver file */
	lp->device = device_create(test_drv_driver_class, NULL, lp->devt,
				     NULL, device_name);
	if (IS_ERR(lp->device)) {
		dev_err(lp->dt_device,
			"couldn't create driver file\n");
		rc = PTR_ERR(lp->device);
		goto err_chrdev_region;
	}
	dev_set_drvdata(lp->device, lp);

	/* create character device */
	cdev_init(&lp->char_device, &fops);
	rc = cdev_add(&lp->char_device, lp->devt, 1);
	if (rc < 0) {
		dev_err(lp->dt_device, "couldn't create character device\n");
		goto err_dev;
	}

	/* create sysfs entries */
	rc = sysfs_create_group(&lp->device->kobj, &test_drv_attrs_group );
	if (rc < 0) {
		dev_err(lp->dt_device, "couldn't register sysfs group\n");
		goto err_cdev;
	}

	dev_info(lp->dt_device, "test-drv created at %pa mapped to 0x%pa, irq=%i, major=%i, minor=%i\n",
		 &lp->mem_start, &lp->base_addr, lp->irq,
		 MAJOR(lp->devt), MINOR(lp->devt));

	
	
	
	
	return 0;
err_cdev:
	cdev_del(&lp->char_device);
err_dev:
	device_destroy(test_drv_driver_class, lp->devt);
err_chrdev_region:
	unregister_chrdev_region(lp->devt, 1);

err_irq:
	free_irq(lp->irq, lp);

err_unmap:	
	iounmap(lp->base_addr);

	
error3:
	free_irq(lp->irq, lp);
error2:
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
error1:
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return rc;
}

static int test_drv_remove(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	struct test_drv_local *lp = dev_get_drvdata(dev);
	free_irq(lp->irq, lp);
	iounmap(lp->base_addr);
	release_mem_region(lp->mem_start, lp->mem_end - lp->mem_start + 1);
	kfree(lp);
	dev_set_drvdata(dev, NULL);
	return 0;
}

#ifdef CONFIG_OF
static struct of_device_id test_drv_of_match[] = {
	{ .compatible = "vendor,test-drv", },
	{ /* end of list */ },
};
MODULE_DEVICE_TABLE(of, test_drv_of_match);
#else
# define test_drv_of_match
#error "why here"
//MODULE_DEVICE_TABLE(platform, platform_device_id);
#endif


static struct platform_driver test_drv_driver = {
	.driver = {
		.name = DRIVER_NAME,
		.owner = THIS_MODULE,
		.of_match_table	= test_drv_of_match,
	},
	.probe		= test_drv_probe,
	.remove		= test_drv_remove,
};

static int __init test_drv_init(void)
{
	test_drv_driver_class = class_create(THIS_MODULE, DRIVER_NAME);
	if (IS_ERR(test_drv_driver_class))
		return PTR_ERR(test_drv_driver_class);


	return platform_driver_register(&test_drv_driver);
}


static void __exit test_drv_exit(void)
{
	platform_driver_unregister(&test_drv_driver);
}

module_init(test_drv_init);
module_exit(test_drv_exit);
